
CARLA_CLASSES_I_TO_NAME = {
    0: 'Unlabeled',
    1: 'Building',
    2: 'Fence',
    3: 'Other',
    4: 'Pedestrian',
    5: 'Pole',
    6: 'RoadLine',
    7: 'Road',
    8: 'SideWalk',
    9: 'Vegetation',
    10: 'Vehicles',
    11: 'Wall',
    12: 'TrafficSign',
    13: 'Sky',
    14: 'Ground',
    15: 'Bridge',
    16: 'RailTrack',
    17: 'GuardRail',
    18: 'TrafficLight',
    19: 'Static',
    20: 'Dynamic',
    21: 'Water',
    22: 'Terrain'
}

NUSCENES_CLASSES_NAME_TO_I = {
    'None': 0,
    'animal': 1,
    'human.pedestrian.adult': 2,
    'human.pedestrian.child': 3,
    'human.pedestrian.construction_worker': 4,
    'human.pedestrian.personal_mobility': 5,
    'human.pedestrian.police_officer': 6,
    'human.pedestrian.stroller': 7,
    'human.pedestrian.wheelchair': 8,
    'movable_object.barrier': 9,
    'movable_object.debris': 10,
    'movable_object.pushable_pullable': 11,
    'movable_object.trafficcone': 12,
    'static_object.bicycle_rack': 13,
    'vehicle.bicycle': 14,
    'vehicle.bus.bendy': 15,
    'vehicle.bus.rigid': 16,
    'vehicle.car': 17,
    'vehicle.construction': 18,
    'vehicle.emergency.ambulance': 19,
    'vehicle.emergency.police': 20,
    'vehicle.motorcycle': 21,
    'vehicle.trailer': 22,
    'vehicle.truck': 23,
    'flat.driveable_surface': 24,
    'vehicle.ego': 31
}

NUSCENES_I_TO_CLASS_NAME = {
    0: 'None',
    1: 'animal',
    2: 'human.pedestrian.adult',
    3: 'human.pedestrian.child',
    4: 'human.pedestrian.construction_worker',
    5: 'human.pedestrian.personal_mobility',
    6: 'human.pedestrian.police_officer',
    7: 'human.pedestrian.stroller',
    8: 'human.pedestrian.wheelchair',
    9: 'movable_object.barrier',
    10: 'movable_object.debris',
    11: 'movable_object.pushable_pullable',
    12: 'movable_object.trafficcone',
    13: 'static_object.bicycle_rack',
    14: 'vehicle.bicycle',
    15: 'vehicle.bus.bendy',
    16: 'vehicle.bus.rigid',
    17: 'vehicle.car',
    18: 'vehicle.construction',
    19: 'vehicle.emergency.ambulance',
    20: 'vehicle.emergency.police',
    21: 'vehicle.motorcycle',
    22: 'vehicle.trailer',
    23: 'vehicle.truck',
    24: 'flat.driveable_surface',
    31: 'vehicle.ego'
}

NUSCENES_COMMON_MAP = {
    0: 0,
    1: 0,
    2: 1,
    3: 1,
    4: 1,
    5: 0,
    6: 1,
    7: 0,
    8: 0,
    9: 0,
    10: 0,
    11: 0,
    12: 0,
    13: 3,
    14: 3,
    15: 3,
    16: 3,
    17: 3,
    18: 3,
    19: 3,
    20: 3,
    21: 3,
    22: 3,
    23: 3,
    24: 2,
    31: 3
}

CARLA_COMMON_MAP = {
    0: 0,
    1: 0,
    2: 0,
    3: 0,
    4: 1,
    5: 0,
    6: 0,
    7: 2,
    8: 0,
    9: 0,
    10: 3,
    11: 0,
    12: 0,
    13: 0,
    14: 0,
    15: 0,
    16: 0,
    17: 0,
    18: 0,
    19: 0,
    20: 0,
    21: 0,
    22: 0,
}

COMMON_NAME_TO_I = {
    0: 'Other',
    1: 'Pedestrian',
    2: 'Road',
    3: 'Vehicle',
}

COMMON_CLASSES_NAME_TO_RGB = {
    0: (0, 0, 0),
    1: (220, 20, 60),
    2: (128, 64, 128),
    3: (0, 0, 142),
}