
config: train_bev_synthetic
exp: 0
model_name: 'syn_bev'
seed: 42

logging:
    log_dir: '/content/drive/MyDrive/spring22/16824/project/atdt/logs/'
    log_interval: 50
    ckpt_dir: '/content/drive/MyDrive/spring22/16824/project/atdt/checkpoints/'

data:
    data_dir: '/content/data/'
    bev_rgb_dir: '/content/data/test/bev/rgb'
    bev_seg_dir: '/content/data/test/bev/seg'
    front_rgb_dir: '/content/data/test/front/rgb'
    front_seg_dir: '/content/data/test/front/seg'

training:
    # Need to modify the class count.
    n_classes: 23
    lr: 0.00001
    lr_step_epochs: 5
    lr_gamma: 0.7
    batch_train: 32
    batch_val: 32
    # Introduce test later.
    train_split: 0.8
    val_split: 0.2
    # Originally - 512, 512
    crop_h: 256
    crop_w: 256
    n_epochs: 70
    n_workers: 0
    start_epoch: 0
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    loss_fn: 'crossentropy'
    metrics: ['iou', 'accuracy']
    arch: 'deeplab_resnet50'
    pretrained: False
    ignore_index: 11
    use_cuda: True