
config: train_bev_synthetic
exp: 0
model_name: 'syn_bev'
seed: 42

logging:
    log_dir: 'logs/'
    log_interval: 50
    ckpt_dir: 'checkpoints/'

data:
    data_dir: 'data/'
    bev_rgb_dir: 'data/syn/bev/rgb'
    bev_seg_dir: 'data/syn/bev/seg'
    front_rgb_dir: 'data/syn/front/rgb'
    front_seg_dir: 'data/syn/front/seg'

training:
    n_classes: 11
    lr: 0.0001
    batch_train: 8
    batch_val: 2
    val_split: 0.2
    crop_h: 512
    crop_w: 512
    n_epochs: 70
    n_workers: 0
    start_epoch: 0
    loss_fn: 'crossentropy'
    metrics: ['iou', 'accuracy']
    arch: 'deeplab_resnet50'
    pretrained: False
    ignore_index: 11
    use_cuda: True